#!/usr/bin/env python3
"""Exact tenant-account NATS permissions; exports remain opt-in.

No credentials, account imports, global administrator wildcard or network access.
The returned blocks belong under a single existing tenant account's users.
"""
import argparse
import json


BASE_STREAMS = ("KV_KELVO_META", "KV_KELVO_JOBS", "KELVO_QUEUE")
EXPORT_STREAMS = ("KV_KELVO_EXPORT_JOBS", "KELVO_EXPORT_QUEUE")
BASE_CONSUMERS = (("KELVO_QUEUE", "dispatch", ""),)
EXPORT_CONSUMERS = (("KELVO_EXPORT_QUEUE", "exports", "export.ready"),)


def tenant_permissions(role, exports=False):
    if role not in ("initializer", "gateway", "worker") or type(exports) is not bool:
        raise ValueError("unknown broker role or export selection")
    streams = BASE_STREAMS + (EXPORT_STREAMS if exports else ())
    consumers = BASE_CONSUMERS + (EXPORT_CONSUMERS if exports else ())
    publish = ["$JS.API.INFO"]
    publish.extend("$JS.API.STREAM.INFO." + stream for stream in streams)
    publish.extend("$JS.API.STREAM.MSG.GET." + stream for stream in streams if stream.startswith("KV_"))
    publish.extend("$JS.API.CONSUMER.INFO." + stream + "." + consumer for stream, consumer, _ in consumers)
    if role == "initializer":
        publish.append("$KV.KELVO_META.meta.config")
        # Initial metadata is read before its direct-access flag is hardened.
        publish.append("$JS.API.DIRECT.GET.KV_KELVO_META.$KV.KELVO_META.meta.config")
        for operation in ("CREATE", "UPDATE", "DELETE"):
            publish.extend("$JS.API.STREAM." + operation + "." + stream for stream in streams)
        for stream, consumer, subject in consumers:
            # Current and legacy exact creation endpoints; no consumer wildcard.
            publish.append("$JS.API.CONSUMER.CREATE." + stream + "." + consumer + ("." + subject if subject else ""))
            publish.append("$JS.API.CONSUMER.DURABLE.CREATE." + stream + "." + consumer)
            publish.append("$JS.API.CONSUMER.DELETE." + stream + "." + consumer)
    else:
        publish.extend(("$KV.KELVO_JOBS.slot.*", "$KV.KELVO_JOBS.worker.*"))
        if exports:
            publish.append("$KV.KELVO_EXPORT_JOBS.export.*")
        if role == "gateway":
            publish.append("job.ready")
            if exports:
                publish.append("export.ready")
        else:
            for stream, consumer, _ in consumers:
                publish.append("$JS.API.CONSUMER.MSG.NEXT." + stream + "." + consumer)
                # Both server ACK forms stay confined to the named queue.
                publish.append("$JS.ACK." + stream + "." + consumer + ".>")
                publish.append("$JS.ACK.*.*." + stream + "." + consumer + ".>")
    return {"publish": {"allow": publish}, "subscribe": {"allow": ["_INBOX.>"]}}


def export_delta(role):
    baseline = tenant_permissions(role, False)["publish"]["allow"]
    enabled = tenant_permissions(role, True)["publish"]["allow"]
    return {"publish": {"allow": [subject for subject in enabled if subject not in baseline]}}


def yaml_document(value, indent=0):
    pad = "  " * indent
    if isinstance(value, dict):
        return "".join(pad + key + ":\n" + yaml_document(child, indent + 1) for key, child in value.items())
    if isinstance(value, list):
        return "".join(pad + "- " + json.dumps(item) + "\n" for item in value)
    raise TypeError("permission documents contain mappings and string lists")


def template():
    return ("# Optional export additions to existing tenant-account user permissions.\n"
            "# Merge allow lists; do not replace existing query/refresh/source-quota grants.\n"
            "# Apply inside one tenant account. This YAML is a permission-block template,\n"
            "# not a complete NATS server configuration or a credential document.\n"
            "# Generated by: python3 scripts/nats_export_permissions.py --template\n"
            + yaml_document({role: export_delta(role) for role in ("initializer", "gateway", "worker")}))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--role", choices=("initializer", "gateway", "worker"))
    parser.add_argument("--exports", action="store_true", help="explicitly add export namespaces")
    parser.add_argument("--template", action="store_true", help="print optional export additions for all roles")
    args = parser.parse_args()
    if args.template:
        if args.role or args.exports:
            parser.error("--template cannot be combined with role or exports")
        print(template(), end="")
    else:
        if args.role is None:
            parser.error("--role is required")
        print(yaml_document(tenant_permissions(args.role, args.exports)), end="")
